const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config({ path: __dirname + '/.env' });

const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/sharebite';

async function purgeTestDonations() {
  try {
    console.log('🔍 Connecting to MongoDB to purge autogenerated test donations & audit logs...');
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB:', mongoUri);

    const Donation = require('./models/Donation');
    const Delivery = require('./models/Delivery');
    const Notification = require('./models/Notification');
    const Review = require('./models/Review');
    const User = require('./models/User');

    // 1. Find all test donations
    const testDonations = await Donation.find({
      $or: [
        { food_name: { $regex: '^Test ', $options: 'i' } },
        { foodName: { $regex: '^Test ', $options: 'i' } },
        { food_name: { $regex: 'Meal Box|Veg Biryani|Chapati|Fruit', $options: 'i' } },
        { donor: { $regex: 'Test|Demo', $options: 'i' } },
      ],
    });

    const testDonationIds = testDonations.map((d) => d._id);
    console.log(`Found ${testDonations.length} test donation records in MongoDB.`);

    // 2. Delete related Delivery tasks
    const delDeliveries = await Delivery.deleteMany({
      $or: [
        { donationId: { $in: testDonationIds } },
        { pickupAddress: { $regex: 'Test', $options: 'i' } },
      ],
    });
    console.log(`Deleted ${delDeliveries.deletedCount} related delivery tasks.`);

    // 3. Delete related Notifications
    const delNotifs = await Notification.deleteMany({
      $or: [
        { relatedDonationId: { $in: testDonationIds } },
        { title: { $regex: 'Test|Demo|Sample', $options: 'i' } },
        { message: { $regex: 'Test Volunteer|Test Self', $options: 'i' } },
      ],
    });
    console.log(`Deleted ${delNotifs.deletedCount} related notifications.`);

    // 4. Delete related Reviews
    const delReviews = await Review.deleteMany({
      donation_id: { $in: testDonationIds },
    });
    console.log(`Deleted ${delReviews.deletedCount} related reviews.`);

    // 5. Delete Test Donations
    const delDonations = await Donation.deleteMany({ _id: { $in: testDonationIds } });
    console.log(`Deleted ${delDonations.deletedCount} test donation records.`);

    // 6. Verify Real User Account csangita0108@gmail.com
    const realUser = await User.findOne({
      email: { $regex: '^csangita0108@gmail.com$', $options: 'i' },
    });

    if (realUser) {
      console.log(`\n✅ VERIFIED: Protected real user account csangita0108@gmail.com exists intact:`);
      console.log(`   Name: ${realUser.name}`);
      console.log(`   Email: ${realUser.email}`);
      console.log(`   Role: ${realUser.role}`);
      console.log(`   isAdmin: ${realUser.isAdmin}`);
      console.log(`   Address: ${realUser.address || realUser.donorAddress || 'Proddatur, Kadapa, Andhra Pradesh'}`);
    } else {
      console.warn(`⚠️ NOTICE: User csangita0108@gmail.com not found.`);
    }

    const remainingDonations = await Donation.countDocuments();
    const remainingDeliveries = await Delivery.countDocuments();
    const remainingNotifications = await Notification.countDocuments();

    console.log('\n--- CLEANUP SUMMARY ---');
    console.log(`Remaining Food Requests in MongoDB: ${remainingDonations}`);
    console.log(`Remaining Active Deliveries: ${remainingDeliveries}`);
    console.log(`Remaining Notifications: ${remainingNotifications}`);
    console.log('✅ Purge of test donations finished successfully!');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error during purge:', error);
    process.exit(1);
  }
}

purgeTestDonations();
